// Generated by scripts/generate-agent-catalog.ts. Do not edit by hand.
import type { ReleaseManifest, ReleaseRecord } from "./hive-contract";
import { recordFromManifest } from "./hive";

const seeds: Array<{ addedAt: number; manifest: ReleaseManifest }> = [
  {
    "addedAt": 1787270400,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "agent.quiet-researcher",
        "name": "Quiet Researcher",
        "version": "1.1.0",
        "category": "research",
        "summary": "Answers a focused question from supplied evidence while keeping facts, gaps, and inference visibly separate.",
        "description": "Examines only the sources and excerpts supplied by the owner, builds a compact evidence trail, identifies disagreements and missing support, and returns a restrained answer without browsing or claiming live verification.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "research",
          "evidence",
          "primary-sources",
          "fact-checking",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/quiet-researcher-1.1.0.agent.json",
        "sha256": "75dee104ecf23b46e9c48ff6926b6f949f4733e1b031fdee6407be23be3d3d02",
        "sizeBytes": 3250,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270340,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.evidence-mapper",
        "name": "Evidence Mapper",
        "version": "1.0.0",
        "category": "research",
        "summary": "Maps supplied claims to their supporting sources, contradictions, confidence limits, and missing evidence.",
        "description": "Builds an auditable claim-to-source map from material provided by the owner so strong support, indirect support, conflicts, and unsupported statements can be reviewed before a decision or publication.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "evidence",
          "claims",
          "sources",
          "verification",
          "research"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/evidence-mapper-1.0.0.agent.json",
        "sha256": "dee9522b7f53454997c28a76497f34e795688299ece0aeeaadad9f6aac8e959b",
        "sizeBytes": 3230,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270280,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.option-comparator",
        "name": "Option Comparator",
        "version": "1.0.0",
        "category": "research",
        "summary": "Compares supplied options against explicit criteria without hiding tradeoffs or choosing for the owner.",
        "description": "Normalizes alternatives described by the owner, tests them against stated constraints and evidence, exposes incomparable or missing information, and produces a decision-ready comparison without making the final choice.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "comparison",
          "decision",
          "criteria",
          "tradeoffs",
          "research"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/option-comparator-1.0.0.agent.json",
        "sha256": "c6c4bce50785c3e8bf3322f8ce1c69b5f5af7cbf7a8fcea2ea5d38cc55a7c7b3",
        "sizeBytes": 3263,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270220,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.code-reviewer",
        "name": "Code Reviewer",
        "version": "1.1.0",
        "category": "development",
        "summary": "Reviews supplied code for concrete correctness, security, regression, and test risks without changing it.",
        "description": "Inspects only the code, patch, and technical context supplied by the owner, prioritizes actionable defects with precise evidence, separates confirmed issues from questions, and never edits or approves a release.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "code-review",
          "correctness",
          "security",
          "regressions",
          "testing"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/code-reviewer-1.1.0.agent.json",
        "sha256": "66b6f14d2f2148c52e2de00929dfe081e7e44928e0cb0b88784258021cb3c6f2",
        "sizeBytes": 3329,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270160,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.spec-auditor",
        "name": "Spec Auditor",
        "version": "1.0.0",
        "category": "development",
        "summary": "Audits supplied specifications for contradictions, gaps, edge cases, and testable acceptance criteria.",
        "description": "Turns a supplied PRD, RFC, requirements document, or implementation plan into a review that links evidence to blocking gaps, ambiguities, missing acceptance criteria, dependencies, and owner questions without choosing the product direction.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "specification",
          "requirements",
          "acceptance-criteria",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/spec-auditor-1.0.0.agent.json",
        "sha256": "f435576dcea3ee0fb71b4766d1e2f6d95da939d3215ea49740a5174c8a018afa",
        "sizeBytes": 2446,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270100,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.bug-triage",
        "name": "Bug Triage",
        "version": "1.0.0",
        "category": "development",
        "summary": "Separates observed failures from hypotheses and recommends the smallest useful next diagnostic.",
        "description": "Analyzes only supplied issue reports, screenshots, logs, stack traces, test failures, and reproduction notes to produce triage linked to evidence without running commands, changing code, or overstating a root cause.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "bugs",
          "triage",
          "diagnostics",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/bug-triage-1.0.0.agent.json",
        "sha256": "6cef11424fd5dcf6ca7cf0239c0ce898711b4d5063437fbf7124411b3ba8539d",
        "sizeBytes": 2441,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787270040,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.reader-tester",
        "name": "Reader Tester",
        "version": "1.0.0",
        "category": "design",
        "summary": "Tests whether a supplied document works for a reader who lacks the author's unstated context.",
        "description": "Evaluates supplied documentation for likely reader questions, ambiguity, hidden assumptions, contradictions, missing context, and priority revisions while preserving the author's voice and avoiding unsolicited rewrites.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "documentation",
          "reader-testing",
          "clarity",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/reader-tester-1.0.0.agent.json",
        "sha256": "9b24ef5084ec20fe9536d35a20823f2b3690ac8a6f441c49b4c08f69cc9f7b1d",
        "sizeBytes": 2489,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269980,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.ux-flow-reviewer",
        "name": "UX Flow Reviewer",
        "version": "1.0.0",
        "category": "design",
        "summary": "Reviews a supplied user flow for friction, missing states, unclear choices, and recovery problems.",
        "description": "Walks through the screens, copy, requirements, or journey supplied by the owner, identifies evidence-backed usability risks and missing states, and suggests prioritized improvements without redesigning outside the stated goal.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "ux",
          "user-flow",
          "usability",
          "states",
          "design-review"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/ux-flow-reviewer-1.0.0.agent.json",
        "sha256": "6b6975a7de696f3eda7edc73e8f546b86f258bc95362f48aa450419a675ef013",
        "sizeBytes": 3338,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269920,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.accessibility-reviewer",
        "name": "Accessibility Reviewer",
        "version": "1.0.0",
        "category": "design",
        "summary": "Finds accessibility risks in supplied interface evidence and turns them into testable review items.",
        "description": "Reviews screenshots, markup excerpts, interaction descriptions, and requirements for perceivable, operable, understandable, and robust use, while avoiding claims that cannot be verified without live testing.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "accessibility",
          "a11y",
          "wcag",
          "inclusive-design",
          "review"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/accessibility-reviewer-1.0.0.agent.json",
        "sha256": "ad6c030573d24b35e8846f48142e19e4a4311e4b8220a219b40ac5645f99a407",
        "sizeBytes": 3352,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269860,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.meeting-synthesizer",
        "name": "Meeting Synthesizer",
        "version": "1.1.0",
        "category": "operations",
        "summary": "Turns supplied meeting material into sourced decisions, open questions, risks, and proposed action items.",
        "description": "Structures notes or transcripts supplied by the owner without inventing consensus, owners, or dates, and distinguishes explicit commitments from suggestions before any follow-up happens elsewhere.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "meetings",
          "decisions",
          "action-items",
          "notes",
          "operations"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/meeting-synthesizer-1.1.0.agent.json",
        "sha256": "7d87b2afd869d0855b642a78cf3cdac9fa4716c3b73b92fa1f6ca38b043e702d",
        "sizeBytes": 3278,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269800,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.decision-recorder",
        "name": "Decision Recorder",
        "version": "1.0.0",
        "category": "operations",
        "summary": "Creates a durable decision record from supplied context, options, rationale, and known consequences.",
        "description": "Converts an owner-approved decision and its evidence into a concise record that preserves status, alternatives, rationale, assumptions, consequences, and revisit triggers without deciding or assigning work.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "decisions",
          "adr",
          "rationale",
          "operations",
          "record"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "buzz-agent",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/decision-recorder-1.0.0.agent.json",
        "sha256": "3b3cf3ef2ec5257dce9a21305822cad79f98a642b6c50a5e5516b0849c9ccd69",
        "sizeBytes": 3243,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269740,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.handoff-builder",
        "name": "Handoff Builder",
        "version": "1.0.0",
        "category": "operations",
        "summary": "Builds a compact handoff that separates current state, verified work, risks, and next operator actions.",
        "description": "Organizes supplied project context into a restartable handoff with state, evidence, decisions, incomplete work, risks, dependencies, and verification steps while avoiding unsupported claims of completion.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "handoff",
          "continuity",
          "status",
          "operations",
          "documentation"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "buzz-agent",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/handoff-builder-1.0.0.agent.json",
        "sha256": "0e5d8126d6a025cf51ce439e69618d3860b8c53e60e8b21ff326f4dd3d7c0818",
        "sizeBytes": 3295,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269680,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.data-explainer",
        "name": "Data Explainer",
        "version": "1.1.0",
        "category": "data",
        "summary": "Explains supplied metrics after checking units, denominators, population, scope, and time windows.",
        "description": "Interprets tables, metric definitions, and calculations supplied by the owner, separates observation from hypothesis, checks comparability, and states clearly what the available data cannot establish.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "data",
          "metrics",
          "analysis",
          "interpretation",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/data-explainer-1.1.0.agent.json",
        "sha256": "bfbb73b9fa19f9866e08689372aeac0e1fcabc83404a824c4d45eb8d4ae5f1e5",
        "sizeBytes": 3325,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269620,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.metric-auditor",
        "name": "Metric Auditor",
        "version": "1.0.0",
        "category": "data",
        "summary": "Audits a metric definition for ambiguity, gaming risk, missing segments, and decision fitness.",
        "description": "Reviews supplied KPI definitions and reporting context, checks formula, population, timing, ownership, exclusions, guardrails, and behavioral incentives, then identifies the smallest changes needed for reliable use.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "metrics",
          "kpi",
          "measurement",
          "data-quality",
          "audit"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/metric-auditor-1.0.0.agent.json",
        "sha256": "4f4781bb443bd20e7e5120366c95b0be024189fb4cba6da1770e7ac594059292",
        "sizeBytes": 3317,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269560,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.experiment-reviewer",
        "name": "Experiment Reviewer",
        "version": "1.0.0",
        "category": "data",
        "summary": "Reviews supplied experiment plans or results for decision validity, bias, and unsupported conclusions.",
        "description": "Checks hypotheses, assignment, exposure, outcomes, guardrails, analysis choices, uncertainty, and practical significance in material supplied by the owner, without recomputing unavailable data or declaring causality by default.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "experiments",
          "ab-testing",
          "causality",
          "statistics",
          "data"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/experiment-reviewer-1.0.0.agent.json",
        "sha256": "384647d3a51d223e10d046643b64e879f99d8bda79f0c22b0e466359f20ad18c",
        "sizeBytes": 3386,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269500,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.draft-polisher",
        "name": "Draft Polisher",
        "version": "1.1.0",
        "category": "marketing",
        "summary": "Edits supplied writing for clarity and voice while preserving facts, uncertainty, and publication control.",
        "description": "Polishes an owner-provided draft, protects names, numbers, links, qualifications, and intended tone, flags unsupported claims, and returns reviewable copy without sending or publishing it.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "editing",
          "writing",
          "claims",
          "voice",
          "marketing"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/draft-polisher-1.1.0.agent.json",
        "sha256": "74a4f92e8389c0ed98d4a3887935b459de78f07357cdaf289dcaef0c895a08b2",
        "sizeBytes": 3325,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269440,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.content-brief-builder",
        "name": "Content Brief Builder",
        "version": "1.0.0",
        "category": "marketing",
        "summary": "Turns supplied goals and evidence into a focused, reviewable content brief without drafting unsupported claims.",
        "description": "Organizes audience, purpose, angle, message, evidence, structure, constraints, and approval questions into a usable brief while preserving the distinction between confirmed inputs and proposed editorial choices.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "content",
          "brief",
          "marketing",
          "editorial",
          "planning"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/content-brief-builder-1.0.0.agent.json",
        "sha256": "15dff3d2d22387394c3980330b785a0e2013bc386545b84e039621c18b32383c",
        "sizeBytes": 3294,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269380,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.claim-guard",
        "name": "Claim Guard",
        "version": "1.0.0",
        "category": "marketing",
        "summary": "Checks supplied public copy for unsupported, overstated, ambiguous, or easily misread claims before release.",
        "description": "Reviews marketing or product copy against evidence supplied by the owner, identifies claims that exceed support or hide important scope, and proposes restrained alternatives without providing legal certification.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "claims",
          "fact-checking",
          "marketing",
          "copy-review",
          "risk"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/claim-guard-1.0.0.agent.json",
        "sha256": "d803d198a89e64f8a9f6b40f296b336e2dba0814220cad9135b1dc4e102c2842",
        "sizeBytes": 3295,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269320,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.threat-modeler",
        "name": "Threat Modeler",
        "version": "1.0.0",
        "category": "security",
        "summary": "Builds threat models from evidence around assets, trust boundaries, abuse paths, and controls.",
        "description": "Produces a defensive threat model from supplied architecture and deployment context, ranks realistic abuse paths, separates assumptions from evidence, and recommends mitigations without probing systems or generating exploit payloads.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "security",
          "threat-model",
          "trust-boundaries",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/threat-modeler-1.0.0.agent.json",
        "sha256": "6742e326c6a83e44bffa0fd2dd74ca11120a436ee0ac203bce918aa7502cb988",
        "sizeBytes": 2579,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269260,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.prompt-safety-reviewer",
        "name": "Prompt Safety Reviewer",
        "version": "1.0.0",
        "category": "security",
        "summary": "Reviews agent prompts for unsafe authority, injection exposure, hidden effects, and unenforceable claims.",
        "description": "Treats a supplied prompt as an untrusted artifact, maps its requested authority, identifies prompt injection and unintended effect risks, and proposes safer wording tied to evidence without executing or following the reviewed instructions.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "prompt-safety",
          "prompt-injection",
          "permissions",
          "read-only"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "claude",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/prompt-safety-reviewer-1.0.0.agent.json",
        "sha256": "6f2e1e6ecf56696c8149d13938fd0646f66027cc3c81d959bfa29507c52d947f",
        "sizeBytes": 2687,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269200,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.privacy-mapper",
        "name": "Privacy Mapper",
        "version": "1.0.0",
        "category": "security",
        "summary": "Maps supplied data flows, purposes, actors, retention, and privacy questions without claiming compliance.",
        "description": "Builds a reviewable privacy map from architecture, process, or policy material supplied by the owner, identifies unclear collection and sharing boundaries, and produces focused questions for product, security, or counsel.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "privacy",
          "data-flow",
          "retention",
          "security",
          "review"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "codex",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/privacy-mapper-1.0.0.agent.json",
        "sha256": "71ac8f8a52b4264ec34c5252703ff7c49da46e6f0ba1b99ea6e20449c1a39399",
        "sizeBytes": 3368,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269140,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.next-step-planner",
        "name": "Next Step Planner",
        "version": "1.0.0",
        "category": "personal",
        "summary": "Turns a supplied goal and current state into a small, realistic next-action plan owned by the user.",
        "description": "Helps the owner reduce an ambiguous personal or work objective into constraints, priorities, a bounded sequence, and review points without accessing calendars, creating tasks, or pretending to manage execution.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "planning",
          "next-actions",
          "priorities",
          "personal",
          "focus"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "buzz-agent",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/next-step-planner-1.0.0.agent.json",
        "sha256": "3d188cfe9469be53086404308f601a094727e946c0f74dd4153238f64cf91b79",
        "sizeBytes": 3347,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269080,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.decision-companion",
        "name": "Decision Companion",
        "version": "1.0.0",
        "category": "personal",
        "summary": "Helps the owner clarify a personal decision, tradeoffs, uncertainty, and reversible ways to learn more.",
        "description": "Structures the options and values supplied by the owner, challenges hidden assumptions, highlights uncertainty and reversibility, and supports reflection without choosing, manipulating, or presenting itself as a professional adviser.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "decision",
          "tradeoffs",
          "reflection",
          "personal",
          "options"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "buzz-agent",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/decision-companion-1.0.0.agent.json",
        "sha256": "361732797ebd5a21a32587cc6a57302386ecc9e0e17214dc10de33a86d8befba",
        "sizeBytes": 3333,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  },
  {
    "addedAt": 1787269020,
    "manifest": {
      "schema": "xyz.hivebuzz.catalog/v1",
      "type": "agent",
      "contributorName": "HiveBuzz examples",
      "release": {
        "id": "xyz.hivebuzz.study-coach",
        "name": "Study Coach",
        "version": "1.0.0",
        "category": "personal",
        "summary": "Builds an active study session from supplied material, goals, and available time without doing the learning for the owner.",
        "description": "Turns notes, excerpts, learning objectives, and constraints into recall questions, practice structure, feedback criteria, and a short review loop while staying within the material the owner provides.",
        "license": "Apache-2.0",
        "homepage": "https://github.com/promptprobe/hivebuzz",
        "keywords": [
          "study",
          "learning",
          "practice",
          "recall",
          "personal"
        ],
        "engines": {
          "buzz": ">=0.9.0"
        },
        "recommendedHarness": "buzz-agent",
        "recommendedModel": "Provider default"
      },
      "artifact": {
        "url": "/agents/study-coach-1.0.0.agent.json",
        "sha256": "49e248dd31ce12e9f9d2b9bfb1326605edffb431b79b823e6feb2b5d6905e93c",
        "sizeBytes": 3248,
        "mediaType": "application/vnd.buzz.agent-snapshot+json"
      },
      "contents": {
        "agents": 1,
        "skills": 0,
        "mcpServers": 0,
        "hooks": 0
      },
      "capabilities": {
        "networkHosts": [],
        "filesystem": "none",
        "commands": [],
        "hooks": [],
        "mcpServers": []
      },
      "snapshot": {
        "format": "buzz-agent-snapshot",
        "version": 1,
        "memoryLevel": "none",
        "identityPolicy": "fresh-on-import",
        "sourceAllowlist": "cleared-on-import"
      }
    }
  }
];

export const CATALOG_RELEASES: ReleaseRecord[] = seeds
  .map(({ manifest, addedAt }) => recordFromManifest(manifest, addedAt))
  .sort((a, b) => b.addedAt - a.addedAt);
